//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento_Chris
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IDempleado { get; set; }
        public string Nombre_Empleado { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Edad { get; set; }
        public Nullable<int> Dias_trabajados { get; set; }
        public Nullable<int> Sueldo_Diario { get; set; }
        public Nullable<int> Planilla_Neto { get; set; }
        public string Contraseña { get; set; }
        public string Genero { get; set; }
        public string Rol { get; set; }
    }
}
