//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento_Chris
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Cod_Producto { get; set; }
        public string Nombre_Producto { get; set; }
        public Nullable<int> Cantidad_Producto { get; set; }
    }
}
